export const CONTACT_LIST_REQUEST = "CONTACT_LIST_REQUEST"
export const CONTACT_LIST_SUCCESS = "CONTACT_LIST_SUCCESS"
export const CONTACT_LIST_FAILURE = "CONTACT_LIST_FAILURE"
export const CONTACT_LIST_UPDATE = "CONTACT_LIST_UPDATE"
export const CONTACT_LIST_AddNEW = "CONTACT_LIST_AddNEW"
export const CONTACT_LIST_FILTER = "CONTACT_LIST_FILTER"
export const CONTACT_LIST_NOT_FILTER = "CONTACT_LIST_NOT_FILTER"


export const ADD_CATEGORY = "ADD_CATEGORY"

export const CallLogs_LIST_REQUEST = "CallLogs_LIST_REQUEST"
export const CallLogs_LIST_SUCCESS = "CallLogs_LIST_SUCCESS"
export const CallLogs_LIST_FAILURE = "CallLogs_LIST_FAILURE"
